### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'results/visualize_test/'

### ISSUE THREAD

**Issue by Qunut999** [HassanBinHaroon/deep-hough-transform#3]
Please help me to resolve this error while I am running the code on cloud at last line (!python test_nkl.py --pred results/visualize_test/ --gt data/NKL/) it shows error file not found.

2023-09-21 07:46:56.311221: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/ot/backend.py:1368: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in array is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  jax.device_put(jnp.array(1, dtype=jnp.float64), d)
2023-09-21 07:47:03.248341: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
/usr/local/lib/python3.10/dist-packages/ot/backend.py:2998: UserWarning: To use TensorflowBackend, you need to activate the tensorflow numpy API. You can activate it by running: 
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()
  register_backend(TensorflowBackend())
Traceback (most recent call last):
  File "/content/deep-hough-transform/test_nkl.py", line 16, in <module>
    filenames = sorted(os.listdir(pred_path))
**FileNotFoundError: [Errno 2] No such file or directory: 'results/visualize_test/'**

**Comment by HassanBinHaroon** [comment]
@Qunut999 Its more than a year since I worked on this project and would take time for error resolution and recall. 

 There's simply a directory missing. Kindly review the code and try to add the directory according to the code.  

Thanks!

**Comment by Qunut999** [comment]
Ok I'll try.

Thank you so much for your response!

**Comment by HassanBinHaroon** [comment]
I see that the issue has been closed.

If its resolved then please post the solution (if possible).

So someone else would be able to resolve the same.

Thanks!

**Comment by Qunut999** [comment]
I am sorry please I didn't try to resolve yet but defiantly I will update when will I resolve.  

Thanks!

**Comment by HassanBinHaroon** [comment]
Okay!

**Comment by Qunut999** [comment]
Greetings!

We've encountered a minor issue, which can be easily resolved by making a simple modification to the code. In the "**forward.py**" file, specifically at line 34, we should substitute this line:

**CONFIGS = yaml.load(open(args.config))**

with this line:

**CONFIGS = yaml.safe_load(open(args.config))**

After making this change, you can proceed to run the following command:

**!python forward.py --model dht_r50_nkl_d97b97138.pth --tmp results**




Once again, **thank you for your attention**.
